### ISSUE TITLE
Need a migration guide for moving from 3.x to 4.x

### ISSUE THREAD

**Issue by wravery** [microsoft/cppgraphqlgen#213]
The migration from 3.x to 4.x is challenging. I've been meaning to start a migration guide based on a couple of samples I've migrated. Here's a list of topics I think should be covered, essentially an outline for the doc (will update with more as they come up):
- [ ] C++17 to C++20:
  - [ ] Describe the toolchain requirements with links to the code and samples.
  - [ ] Describe how to use custom Awaitables with links to the unit tests.
  - [ ] Describe how to implement field accessors as a coroutine.
- [ ] Removing inheritance and replacing with type-erased wrappers:
  - [ ] Change the class declaration, potentially add `std::enable_shared_from_this<>`.
  - [ ] Make `override` or `final` field accessors non-virtual.
  - [ ] Wrapping type-erased `type` objects with `interface` and `union` objects.
  - [ ] Decoupling an inheritance hierarchy from `service::Object` (#210)
- [ ] Simplify the field accessor signatures:
  - [ ] Return wrapped types directly (unless implementing a coroutine).
  - [ ] Make methods `const` or non-`const` as appropriate (can also get rid of a lot of `mutable` member variables this way).
  - [ ] Pass parameters by `const&` reference, `&&` r-value reference, or value.
  - [ ] Drop unused `service::FieldParams` arguments.
- [ ] Using the new CMake functions:
  - [ ] ⚠️ Potentially destructive, build the schema in a sub-directory and use source control (i.e. Git) before and after (#212).
  - [ ] Migrating from the unified output to what would have been generated with `--separate-files`
  - [ ] Removing the `graphqlintrospection` target (#196)
- [ ] Links to migration commits in sample and external projects:
  - [ ] gqlmapi
  - [ ] electron-cppgraphql
  - [ ] samples in this repo (e.g. replacing all of the "unified" schemas with `--separate-files` versions, converting `TodayMock.*` implementations, etc.)
